//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemist
    {
        public int chemistID { get; set; }
        public string chemistName { get; set; }
        public string chemistAddress { get; set; }
        public string chemistEmail { get; set; }
        public string chemistContact { get; set; }
        public string chemistDescription { get; set; }
    }
}
