//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderHeader
    {
        public int purchaseOrderID { get; set; }
        public System.DateTime purchaseOrderDate { get; set; }
        public int purchaseOrderSupplierID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual PurchaseProductLine PurchaseProductLine { get; set; }
    }
}
